mongo2:
  hostname: mongo2
  image: mongo:3.0
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27018:27017"
    - "28018:28017"

mongo3:
  hostname: mongo3
  image: mongo:3.0
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27019:27017"
    - "28019:28017"

mongo1:
  hostname: mongo1
  image: mongo:3.0
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27017:27017"
    - "28017:28017"
  links:
    - mongo2:mongo2
    - mongo3:mongo3

# The official elasticsearch:1.4.2 image with mapper-attachments and river-mongodb plugins
# https://github.com/soldotno/elasticsearch-river-mongodb/blob/master/Dockerfile
elasticsearch:
  ports:
    - "9200:9200"
    - "9300:9300"
  image: stabenfeldt/elasticsearch-river-mongodb
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3

mongosetup:
  image: mongo:3.0
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/setup.sh" ]

## This image downloads the json file spesified in RIVER_MAPPING and informs elasticsearch
#  of which database and collection to index.
#  https://github.com/soldotno/elasticsearch-river-setup/blob/master/Dockerfile
elasticsearchriversetup:
  image: "stabenfeldt/elasticsearch-river-setup"
  links:
    - elasticsearch:elasticsearch
  environment:
    RIVER_MAPPING: "https://raw.githubusercontent.com/soldotno/harvester/master/mapping.json?token=AALEGLmwZz7iowiXWvcZwppW82K_gtZsks5VqPkLwA%3D%3D"
    RIVER_NAME: "harvester"

removesharding:
  image: mongo:3.0
  links:
    - elasticsearch:elasticsearch
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/remove-sharding.sh" ]

insertdataqueryes:
  image: mongo:3.0
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
    - elasticsearch:elasticsearch
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/query.sh" ]
