# To get ES and MongoDB do play with each other, we need a MongoDB replicaset and Elasticsearch.
# Elasticsearch with rivers for mongodb
elasticsearch:
  ports:
    - "9200:9200"
    - "9300:9300"
  image: stabenfeldt/elasticsearch-river-mongodb


mongo2:
  hostname: mongo2
  image: mongo:3.0
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles" ]
  ports:
    - "27018:27017"

mongo3:
  hostname: mongo3
  image: mongo:3.0
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles" ]
  ports:
    - "27019:27017"

mongo1:
  hostname: mongo1
  image: mongo:3.0
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles" ]
  ports:
    - "27017:27017"
  links:
    - mongo2:mongo2
    - mongo3:mongo3


mongosetup:
  image: mongo:3.0
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/setup.sh" ]

## This image downloads mappings.json and informs elasticsearch of which database and collection to index
elasticsearchriversetup:
  image: "stabenfeldt/elasticsearch-river-setup"
  environment:
    MAPPING_FILE: "https://raw.githubusercontent.com/soldotno/harvester-webservice/feature/es-back/setup-harvester-index.json?token=AALEGGpgMJ9YjgBmtULOjOzYDwzXB7KXks5VllWqwA%3D%3D"
    RIVER_NAME: "harvester"


